version: '3.3' 
services:
  frontend: # 1st service
    build: ./frontend
    ports:
        - '9000:80'
    container_name: front-container

  backend: #2nd service
    build: ./backend 
    ports:
      - '3000:3000' 
    container_name: back-container
