version: '3.3' # specify docker-compose version
# Define the services/containers to be run
services:
  frontend:
    build: ./frontend
    ports:
        - '9000:80'
    container_name: front-container

  backend: #name of the second service
    build: ./backend # specify the directory of the Dockerfile
    ports:
      - '3000:3000' #specify ports forewarding
    container_name: back-container
